/***************************************************************
 *  SmartRF Studio(tm) Export
 *
 *  Radio register settings specifed with C-code
 *  compatible #define statements.
 *
 ***************************************************************/

#ifndef SMARTRF_CC430_H
#define SMARTRF_CC430_H

#define SMARTRF_RADIO_CC430

#define SMARTRF_SETTING_FSCTRL1    0x08
#define SMARTRF_SETTING_FSCTRL0    0x00
#define SMARTRF_SETTING_FREQ2      0x23
#define SMARTRF_SETTING_FREQ1      0x44
#define SMARTRF_SETTING_FREQ0      0xEC
#define SMARTRF_SETTING_MDMCFG4    0xCA
#define SMARTRF_SETTING_MDMCFG3    0x83
#define SMARTRF_SETTING_MDMCFG2    0x93
#define SMARTRF_SETTING_MDMCFG1    0x22
#define SMARTRF_SETTING_MDMCFG0    0xF8
#define SMARTRF_SETTING_CHANNR     0x30
#define SMARTRF_SETTING_DEVIATN    0x34
#define SMARTRF_SETTING_FREND1     0x56
#define SMARTRF_SETTING_FREND0     0x10
#define SMARTRF_SETTING_MCSM0      0x18
#define SMARTRF_SETTING_FOCCFG     0x16
#define SMARTRF_SETTING_BSCFG      0x6C
#define SMARTRF_SETTING_AGCCTRL2   0x43
#define SMARTRF_SETTING_AGCCTRL1   0x40
#define SMARTRF_SETTING_AGCCTRL0   0x91
#define SMARTRF_SETTING_FSCAL3     0xE9
#define SMARTRF_SETTING_FSCAL2     0x2A
#define SMARTRF_SETTING_FSCAL1     0x00
#define SMARTRF_SETTING_FSCAL0     0x1F
#define SMARTRF_SETTING_FSTEST     0x59
#define SMARTRF_SETTING_TEST2      0x81
#define SMARTRF_SETTING_TEST1      0x35
#define SMARTRF_SETTING_TEST0      0x09
#define SMARTRF_SETTING_FIFOTHR    0x47
#define SMARTRF_SETTING_IOCFG2     0x29
#define SMARTRF_SETTING_IOCFG0D    0x06

#define SMARTRF_SETTING_PKTCTRL1   0x0C
#define SMARTRF_SETTING_PKTCTRL0   0x44
#define SMARTRF_SETTING_ADDR       0x00
#define SMARTRF_SETTING_PKTLEN     0x16

#define SMARTRF_SETTING_WOREVT1    0x80
#define SMARTRF_SETTING_WOREVT0    0x00
#define SMARTRF_SETTING_WORCTRL    0xF0
#define SMARTRF_SETTING_IOCFG1     0x2E
#define SMARTRF_SETTING_IOCFG0     0x2E
#define SMARTRF_SETTING_SYNC1      0xD3
#define SMARTRF_SETTING_SYNC0      0x91
#define SMARTRF_SETTING_MCSM2      0x07
#define SMARTRF_SETTING_MCSM1      0x30

#define SMARTRF_SETTING_PATABLE0   0x1E
#define SMARTRF_SETTING_PATABLE1   0x1E
#define SMARTRF_SETTING_PATABLE2   0x1E
#define SMARTRF_SETTING_PATABLE3   0x1E
#define SMARTRF_SETTING_PATABLE4   0x1E
#define SMARTRF_SETTING_PATABLE5   0x1E
#define SMARTRF_SETTING_PATABLE6   0x1E
#define SMARTRF_SETTING_PATABLE7   0x1E

#define SMARTRF_SETTING_PTEST      0x7F
#define SMARTRF_SETTING_AGCTEST    0x3F
#endif


